### ISSUE TITLE
Authentication failed for admin token

### ISSUE THREAD

**Issue by sc0rp10** [monitorjbl/stash-token-auth#22]
Hi!
I'm trying to use this plugin, but I cannot get work admin tokens.

I'm using `Atlassian Bitbucket 4.14.3` and `com.thundermoose.plugins.stash-token-auth v2.2` from marketplace.

I've created an admin token with all permissions:
![Image of Yaktocat](https://cdn.weblab.pro/6kyoq.png)

Next, i tried to made api call:
```
curl -H "X-Auth-User:admin" -H "X-Auth-Token:fiEEkoX16MKQOBDNSypFpw==" -H "Content-Type: application/json" http://hostname/rest/api/1.0/projects/PROJ/repos
```

But request failed with:
```json
{
  "errors": [
    {
      "context": null,
      "message": "Authentication failed. Please check your credentials and try again.",
      "exceptionName": "com.thundermoose.plugins.TokenAuthenticationException"
    }
  ]
}
```

Whats my mistake? How should I setup plugin for correct authenticating?

**Comment by monitorjbl** [comment]
That isn't your token, that's the private server key used to decrypt tokens. Every user gets his own token, which is visible in the user's account detail page.
