### ISSUE TITLE
Add support for Branch Permissions API

### ISSUE THREAD

**Issue by maciejharczuk** [monitorjbl/stash-token-auth#3]
Trying to use token auth with Branch Permissions API (https://developer.atlassian.com/static/rest/stash/3.8.0/stash-branch-permissions-rest.html) results in an AuthorisationException.

**Comment by monitorjbl** [comment]
I'll try and get this verified on my end and released out this week.

**Comment by monitorjbl** [comment]
This fix is available now in version 1.5.
