### ISSUE TITLE
Build integration

### ISSUE THREAD

**Issue by deatharse** [monitorjbl/stash-token-auth#5]
Feature Request:

Please add support for build-status api endpoint in the allowed paths

[Build integration documentation](https://developer.atlassian.com/static/rest/stash/3.6.0/stash-build-integration-rest.html#resources)

i.e.

```
http://localhost/rest/build-status/1.0/commits/<commit-id>
```

**Comment by monitorjbl** [comment]
Yep, that seems like a good idea. I'll get that added in.

**Comment by monitorjbl** [comment]
This fix is available now in version 1.5.

**Comment by deatharse** [comment]
Nice one :)
