### ISSUE TITLE
Token Expiry

### ISSUE THREAD

**Issue by deatharse** [monitorjbl/stash-token-auth#6]
Is there a currently a method to alert you when the REST tokens have expired.  I use this for hooking into [PHPCI](https://github.com/Block8/PHPCI) so send back the build status and twice in the last month when it wasnt working after some debugging realised the token PHPCI was configured to use had expired (confirmed by means of curl requests to Stash API)?

Still not sure the reason the tokens expired though but it did seem to be all user tokens.  Not sure if this is a generic Stash Token API issue (i.e. Atlassian) or a Token Authenticator issue (yourself).

**Comment by monitorjbl** [comment]
There's not an email alert @alasdairdc , but I suspect you don't actually need one. The tokens by default expire in 30 days after they are generated. It sounds like you'd rather they never expire, which is an option as of version 1.4. All you have to do is set the Token Expiry field in the admin UI to `0`. Any new tokens issued _after_ that change will never expire.

**Comment by deatharse** [comment]
D'oh! Many thanks that's what I was looking for.
