### ISSUE TITLE
Support rest endpoint '/rest/api/1.0/projects'

### ISSUE THREAD

**Issue by dozius** [monitorjbl/stash-token-auth#7]
I would like to be able to retrieve a list of projects using the rest endpoint '/rest/api/1.0/projects'. Currently this doesn't appear in the list on the config page and trying to access it returns an authentication error.

**Comment by monitorjbl** [comment]
Sorry for the delay in responding, I'll get this added in ASAP

**Comment by dozius** [comment]
Great, thanks!

**Comment by monitorjbl** [comment]
@dozius This is fixed in version 1.7, which is now available on the Atlassian Marketplace.

**Comment by dozius** [comment]
Working here. Thanks again!
